### ISSUE TITLE
Issue with ASIN and ISBN

### ISSUE THREAD

**Issue by Hytalecreed** [havanagrawal/GoodreadsScraper#6]
Yeah it works now, Thank you very much. But ISBN and ASIN doesn't work, maybe they changed the class or something. I am not sure.

`'isbn' : response.css('#bookDataBox > div:nth-child(2) > div.infoBoxRowItem > span > span::text').get()`

I used the above code to write my own spider and it works but I still should find a way to make ASIN working.

And is there any way to get most popular [reviews](https://www.goodreads.com/api/index#review.show) and amazon link of the book? 

Thank you.

**Comment by havanagrawal** [comment]
Hi,

Thanks for pointing this out, yes they do keep changing the css path. There's an outstanding bug #3 that I mean to address soon.

In the meanwhile, I've just pushed 98f7060934a4345fed1c2ecffa9b10dc09eb45f3 which has more robust extraction for the `isbn` and `isbn13` values (which are now separate fields in the resulting json).

Note that [according to Wikipedia](https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number), for books with 10-digit International Standard Book Number (ISBN), the ASIN and the ISBN are the same. This means that while the ASIN may not be explicitly populated, it is derivable for most records.

The Amazon product link for a book with some isbn10/asin is `www.amazon.com/dp/{asin}`

For example, 
 1. The isbn for [Collected Sonnets](https://www.goodreads.com/book/show/60322.Collected_Sonnets) is `0060910917`. The Amazon product link is www.amazon.com/dp/0060910917
2. The asin for [A Witch's Welcome](https://www.goodreads.com/book/show/16166449-a-witch-s-welcome) is `B00AB06S9G`. The Amazon product link is www.amazon.com/dp/B00AB06S9G

For _most popular_ reviews, unfortunately I don't believe this is easy as of today, since Goodreads does not have a sort order for popularity for their reviews. It looks like it should be fairly simple, however, to get the reviews that are visible on the page when you visit it.

I'll create a separate tracking bug for extracting reviews. :)

Cheers.

**Comment by Hytalecreed** [comment]
Thanks for the update and quick response!
